/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const amplifyConfig = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:dff70bed-4cc3-4139-8473-83315c79fab4",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_CYr00rKJf",
    "aws_user_pools_web_client_id": "4u98qpjujl0j1bu42m6ib72bcb",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://kos6kupeanadxb3meckroezliy.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


window.amplifyConfig = amplifyConfig;
